Repository TEAM-DoDream/DoDream_BE, pull requests merged in 2025-04, with the labels that each got.

#9 Fix : Dockerfile java 17->21로 변경한다
  Dockerfile
Labels: 📌 setting

#13 Feat : cicd.yml를 작성하고 build.gradle에 분기 처리를 추가한다
  .github/workflows/ci-cd.yml
  build.gradle
Labels: 📌 setting

#15 Fix : yml파일이 모두 복사된 이후에 compile되도록 dependsOn 추가한다.
  build.gradle
Labels: ❌ bug, 📌 setting

#17 Fix : build.gradle내의 copyAppYml, copyDockerCompose task 순서를 설정한다.
  build.gradle
Labels: ❌ bug

#21 Fix : cicd의 NCP접속 username을 변경하여 접속 오류를 해결한다.
  .github/workflows/ci-cd.yml
Labels: ❌ bug

#28 Fix : cicd.yml - docker compose로 명령어를 변경한다
  .github/workflows/ci-cd.yml
Labels: 🚨 bug

#44 Fix(#42): mysql connector 버전을 변경한다.
  gradle/db.gradle
Labels: 🚨 bug
