Repository TEAM-DoDream/DoDream_BE, pull requests merged in 2025-05, with the labels that each got.

#102 Refactor(#101): 변수명을 memberId에서 loginId로 변경한다
  src/main/java/com/dodream/member/application/MemberAuthService.java
  src/main/java/com/dodream/member/presentation/controller/MemberAuthController.java
  src/main/java/com/dodream/member/presentation/swagger/MemberAuthSwagger.java
Labels: 🔄 refactor

#115 Refactor(#114) : validation 관련 annotation과 gradle을 수정한다.
  gradle/spring.gradle
  src/main/java/com/dodream/member/dto/request/ChangeMemberBirthDateRequestDto.java
  src/main/java/com/dodream/member/dto/request/MemberSignUpRequestDto.java
  src/main/java/com/dodream/member/presentation/swagger/MemberAuthSwagger.java
Labels: 🔄 refactor

#117 Refactor(#116) : 거주지 없어도 로그인시 NE 발생하지 않도록 수정한다.
  src/main/java/com/dodream/member/application/MemberAuthService.java
Labels: 🔄 refactor

#124 Fix(#123): 사람인 API 버그 개선전까지 마감일 검색 기능을 비활성화 한다.
  src/main/java/com/dodream/recruit/infrastructure/RecruitApiCaller.java
  src/main/java/com/dodream/recruit/infrastructure/RecruitFeignClient.java
  src/main/java/com/dodream/training/infrastructure/caller/BootCampApiCaller.java
  src/main/java/com/dodream/training/infrastructure/caller/DualTrainingApiCaller.java
Labels: 🚨 bug

#164 Feat(#163): 직업 리스트 조회시 이미지 나오도록 수정
  src/main/java/com/dodream/job/application/JobRecommendService.java
  src/main/java/com/dodream/job/application/JobService.java
  src/main/java/com/dodream/job/dto/response/JobListDto.java
  src/main/java/com/dodream/job/infrastructure/JobImageUrlGenerator.java
Labels: ⭐️ feat

#176 Feat(#175): 훈련과정에 마감일 정렬 필터를 추가한다.
  src/main/java/com/dodream/training/application/BootcampService.java
  src/main/java/com/dodream/training/application/DualTrainingService.java
  src/main/java/com/dodream/training/infrastructure/caller/BootCampApiCaller.java
  src/main/java/com/dodream/training/infrastructure/caller/DualTrainingApiCaller.java
  src/main/java/com/dodream/training/infrastructure/caller/TrainingApiCaller.java
  src/main/java/com/dodream/training/presentation/controller/TrainingController.java
  src/main/java/com/dodream/training/presentation/swagger/TrainingSwagger.java
  src/main/java/com/dodream/training/presentation/value/SortBy.java
  src/main/java/com/dodream/training/util/executer/BootcampApiExecuter.java
  src/main/java/com/dodream/training/util/executer/DualTrainingApiExecuter.java
  src/main/java/com/dodream/training/util/executer/TrainingApiExecuter.java
Labels: ⭐️ feat, 🔄 refactor

#194 Refactor(#193) : 회원 탈퇴 로직을 수정한다.
  src/main/java/com/dodream/member/application/MemberAuthService.java
  src/main/java/com/dodream/member/domain/Member.java
  src/main/java/com/dodream/scrap/repository/MemberRecruitScrapRepository.java
  src/main/java/com/dodream/scrap/repository/MemberTrainingScrapRepository.java
  src/main/java/com/dodream/todo/repository/TodoGroupRepository.java
Labels: 🔄 refactor

#205 Fix(#204): 훈련비용이 0원으로 저장되는 오류를 수정한다.
  src/main/java/com/dodream/scrap/domain/entity/MemberTrainingScrap.java
  src/main/java/com/dodream/training/dto/response/TrainingDetailApiResponse.java
  src/test/java/com/dodream/scrap/application/TrainingScrapServiceTest.java
  src/test/java/com/dodream/training/application/AbstractTrainingServiceTest.java
Labels: 🚨 bug

#207 feat(#206) : 프로필 삭제 api를 구현한다
  src/main/java/com/dodream/member/application/MemberService.java
  src/main/java/com/dodream/member/dto/response/DeleteMemberProfileImageResponseDto.java
  src/main/java/com/dodream/member/exception/MemberErrorCode.java
  src/main/java/com/dodream/member/presentation/controller/MemberController.java
  src/main/java/com/dodream/member/presentation/swagger/MemberSwagger.java
Labels: ⭐️ feat

#216 Fix(#215): 유저가 직업담기를 하지않은 경우에 예외처리 수정
  src/main/java/com/dodream/recruit/application/RecruitService.java
Labels: 🚨 bug
