Repository TEAM-DoDream/DoDream_BE, pull requests merged in 2025-08, with the labels that each got.

#246 feat : 직업 삭제 api 구현
  src/main/java/com/dodream/member/application/MemberService.java
  src/main/java/com/dodream/todo/application/TodoMemberService.java
  src/main/java/com/dodream/todo/dto/response/DeleteMemberJobResponseDto.java
  src/main/java/com/dodream/todo/presentation/controller/TodoMemberController.java
  src/main/java/com/dodream/todo/presentation/swagger/TodoMemberSwagger.java
Labels: ⭐️ feat

#248 bugfix : logController - catch문에 throw문을 추가한다.
  src/main/java/com/dodream/core/infrastructure/log/LoggingAspect.java
Labels: 🚨 bug

#253 Feat(#252): 다른 사람 Todo 조회시 지역 정보 함께 조회하도록 변경
  gradle/jwt.gradle
  src/main/java/com/dodream/todo/dto/response/GetOneTodoGroupResponseDto.java
Labels: ⭐️ feat

#261 Refactor(#260) : 직업 todo enum 값을 변경한다
  src/main/java/com/dodream/job/domain/TodoCategory.java
Labels: 🔄 refactor
